In [4]:
import pandas as pd

In [5]:
df =pd.read_csv("Loans.csv")

In [6]:
df.columns

Index(['Unnamed: 0', 'emp_title', 'emp_length', 'state', 'homeownership',
       'annual_income', 'verified_income', 'debt_to_income',
       'annual_income_joint', 'verification_income_joint',
       'debt_to_income_joint', 'delinq_2y', 'months_since_last_delinq',
       'earliest_credit_line', 'inquiries_last_12m', 'total_credit_lines',
       'open_credit_lines', 'total_credit_limit', 'total_credit_utilized',
       'num_collections_last_12m', 'num_historical_failed_to_pay',
       'months_since_90d_late', 'current_accounts_delinq',
       'total_collection_amount_ever', 'current_installment_accounts',
       'accounts_opened_24m', 'months_since_last_credit_inquiry',
       'num_satisfactory_accounts', 'num_accounts_120d_past_due',
       'num_accounts_30d_past_due', 'num_active_debit_accounts',
       'total_debit_limit', 'num_total_cc_accounts', 'num_open_cc_accounts',
       'num_cc_carrying_balance', 'num_mort_accounts',
       'account_never_delinq_percent', 'tax_liens', 'public_record_bankrupt',
       'loan_purpose', 'application_type', 'loan_amount', 'term',
       'interest_rate', 'installment', 'grade', 'sub_grade', 'issue_month',
       'loan_status', 'initial_listing_status', 'disbursement_method',
       'balance', 'paid_total', 'paid_principal', 'paid_interest',
       'paid_late_fees'],
      dtype='object')

In [7]:
df.shape

(10000, 56)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 56 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        10000 non-null  int64
 1   emp_title                         9167 non-null   object
 2   emp_length                        9183 non-null   float64
 3   state                             10000 non-null  object
 4   homeownership                     10000 non-null  object
 5   annual_income                     10000 non-null  float64
 6   verified_income                   10000 non-null  object
 7   debt_to_income                    9976 non-null   float64
 8   annual_income_joint               1495 non-null   float64
 9   verification_income_joint         1455 non-null   object
 10  debt_to_income_joint              1495 non-null   float64
 11  delinq_2y                         10000 non-null  int64
 12  months_since_last_delinq          4342 non-null   float64
 13  earliest_credit_line              10000 non-null  int64
 14  inquiries_last_12m                10000 non-null  int64
 15  total_credit_lines                10000 non-null  int64
 16  open_credit_lines                 10000 non-null  int64
 17  total_credit_limit                10000 non-null  int64
 18  total_credit_utilized             10000 non-null  int64
 19  num_collections_last_12m          10000 non-null  int64
 20  num_historical_failed_to_pay      10000 non-null  int64
 21  months_since_90d_late             2285 non-null   float64
 22  current_accounts_delinq           10000 non-null  int64
 23  total_collection_amount_ever      10000 non-null  int64
 24  current_installment_accounts      10000 non-null  int64
 25  accounts_opened_24m               10000 non-null  int64
 26  months_since_last_credit_inquiry  8729 non-null   float64
 27  num_satisfactory_accounts         10000 non-null  int64
 28  num_accounts_120d_past_due        9682 non-null   float64
 29  num_accounts_30d_past_due         10000 non-null  int64
 30  num_active_debit_accounts         10000 non-null  int64
 31  total_debit_limit                 10000 non-null  int64
 32  num_total_cc_accounts             10000 non-null  int64
 33  num_open_cc_accounts              10000 non-null  int64
 34  num_cc_carrying_balance           10000 non-null  int64
 35  num_mort_accounts                 10000 non-null  int64
 36  account_never_delinq_percent      10000 non-null  float64
 37  tax_liens                         10000 non-null  int64
 38  public_record_bankrupt            10000 non-null  int64
 39  loan_purpose                      10000 non-null  object
 40  application_type                  10000 non-null  object
 41  loan_amount                       10000 non-null  int64
 42  term                              10000 non-null  int64
 43  interest_rate                     10000 non-null  float64
 44  installment                       10000 non-null  float64
 45  grade                             10000 non-null  object
 46  sub_grade                         10000 non-null  object
 47  issue_month                       10000 non-null  object
 48  loan_status                       10000 non-null  object
 49  initial_listing_status            10000 non-null  object
 50  disbursement_method               10000 non-null  object
 51  balance                           10000 non-null  float64
 52  paid_total                        10000 non-null  float64
 53  paid_principal                    10000 non-null  float64
 54  paid_interest                     10000 non-null  float64
 55  paid_late_fees                    10000 non-null  float64
dtypes: float64(17), int64(26), object(13)
memory usage: 4.3+ MB

In [9]:
df.head()

,Unnamed: 0,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,1,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,...,C3,Mar-18,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,2,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,...,C1,Feb-18,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,3,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,...,D1,Feb-18,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,4,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,...,A3,Jan-18,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,5,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,...,C3,Mar-18,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0

In [10]:
df.isnull().sum().sort_values(ascending=False)

verification_income_joint           8545
annual_income_joint                 8505
debt_to_income_joint                8505
months_since_90d_late               7715
months_since_last_delinq            5658
months_since_last_credit_inquiry    1271
emp_title                            833
emp_length                           817
num_accounts_120d_past_due           318
debt_to_income                        24
interest_rate                          0
tax_liens                              0
account_never_delinq_percent           0
public_record_bankrupt                 0
loan_purpose                           0
application_type                       0
loan_amount                            0
num_mort_accounts                      0
term                                   0
sub_grade                              0
installment                            0
grade                                  0
num_open_cc_accounts                   0
issue_month                            0
loan_status                            0
initial_listing_status                 0
disbursement_method                    0
balance                                0
paid_total                             0
paid_principal                         0
paid_interest                          0
num_cc_carrying_balance                0
Unnamed: 0                             0
num_total_cc_accounts                  0
total_credit_limit                     0
state                                  0
homeownership                          0
annual_income                          0
verified_income                        0
delinq_2y                              0
earliest_credit_line                   0
inquiries_last_12m                     0
total_credit_lines                     0
open_credit_lines                      0
total_credit_utilized                  0
total_debit_limit                      0
num_collections_last_12m               0
num_historical_failed_to_pay           0
current_accounts_delinq                0
total_collection_amount_ever           0
current_installment_accounts           0
accounts_opened_24m                    0
num_satisfactory_accounts              0
num_accounts_30d_past_due              0
num_active_debit_accounts              0
paid_late_fees                         0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
for col in ['homeownership', 'verified_income', 'loan_purpose',
            'application_type', 'term', 'grade', 'loan_status']:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 homeownership
homeownership
MORTGAGE    4789
RENT        3858
OWN         1353
Name: count, dtype: int64

 verified_income
verified_income
Source Verified    4116
Not Verified       3594
Verified           2290
Name: count, dtype: int64

 loan_purpose
loan_purpose
debt_consolidation    5144
credit_card           2249
other                  914
home_improvement       680
major_purchase         303
medical                162
house                  151
car                    131
small_business         125
moving                  69
vacation                62
renewable_energy        10
Name: count, dtype: int64

 application_type
application_type
individual    8505
joint         1495
Name: count, dtype: int64

 term
term
36    6970
60    3030
Name: count, dtype: int64

 grade
grade
B    3037
C    2653
A    2459
D    1446
E     335
F      58
G      12
Name: count, dtype: int64

 loan_status
loan_status
Current               9375
Fully Paid             447
In Grace Period         67
Late (31-120 days)      66
Late (16-30 days)       38
Charged Off              7
Name: count, dtype: int64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,10000.0,5000.500000,2886.895680,1.00,2500.7500,5000.500,7500.2500,1.000000e+04
emp_length,9183.0,5.930306,3.703734,0.00,2.0000,6.000,10.0000,1.000000e+01
annual_income,10000.0,79222.148412,64734.290492,0.00,45000.0000,65000.000,95000.0000,2.300000e+06
debt_to_income,9976.0,19.308192,15.004851,0.00,11.0575,17.570,25.0025,4.690900e+02
annual_income_joint,1495.0,127914.571244,70168.375404,19200.00,86833.5000,113000.000,151545.5000,1.100000e+06
debt_to_income_joint,1495.0,19.979304,8.054781,0.32,14.1600,19.720,25.5000,3.998000e+01
delinq_2y,10000.0,0.216000,0.683660,0.00,0.0000,0.000,0.0000,1.300000e+01
months_since_last_delinq,4342.0,36.760709,21.634939,1.00,19.0000,34.000,53.0000,1.180000e+02
earliest_credit_line,10000.0,2001.290000,7.795510,1963.00,1997.0000,2003.000,2006.0000,2.015000e+03
inquiries_last_12m,10000.0,1.958200,2.380130,0.00,0.0000,1.000,3.0000,2.900000e+01
total_credit_lines,10000.0,22.679600,11.885439,2.00,14.0000,21.000,29.0000,8.700000e+01
open_credit_lines,10000.0,11.404400,5.868280,0.00,7.0000,10.000,14.0000,5.100000e+01
total_credit_limit,10000.0,183606.230400,187632.707777,0.00,51593.7500,114667.000,267550.0000,3.386034e+06
total_credit_utilized,10000.0,51049.063100,53636.731172,0.00,19185.5000,36927.000,65421.0000,9.424560e+05
num_collections_last_12m,10000.0,0.013800,0.126535,0.00,0.0000,0.000,0.0000,3.000000e+00
num_historical_failed_to_pay,10000.0,0.167100,0.687768,0.00,0.0000,0.000,0.0000,5.200000e+01
months_since_90d_late,2285.0,46.112473,21.748021,2.00,29.0000,47.000,63.0000,1.280000e+02
current_accounts_delinq,10000.0,0.000100,0.010000,0.00,0.0000,0.000,0.0000,1.000000e+00
total_collection_amount_ever,10000.0,184.334000,2206.389859,0.00,0.0000,0.000,0.0000,1.993080e+05
current_installment_accounts,10000.0,2.663600,2.935387,0.00,1.0000,2.000,3.0000,3.500000e+01
accounts_opened_24m,10000.0,4.376100,3.158583,0.00,2.0000,4.000,6.0000,2.900000e+01
months_since_last_credit_inquiry,8729.0,7.340703,5.981590,0.00,2.0000,6.000,11.0000,2.400000e+01
num_satisfactory_accounts,10000.0,11.379600,5.859705,0.00,7.0000,10.000,14.0000,5.100000e+01
num_accounts_120d_past_due,9682.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.000000e+00
num_accounts_30d_past_due,10000.0,0.000100,0.010000,0.00,0.0000,0.000,0.0000,1.000000e+00
num_active_debit_accounts,10000.0,3.595300,2.434689,0.00,2.0000,3.000,5.0000,3.200000e+01
total_debit_limit,10000.0,27357.410300,26570.164081,0.00,10000.0000,19500.000,36100.0000,3.867000e+05
num_total_cc_accounts,10000.0,13.030000,7.874713,2.00,7.0000,11.000,17.0000,6.600000e+01
num_open_cc_accounts,10000.0,8.095000,4.906606,0.00,5.0000,7.000,10.0000,4.600000e+01
num_cc_carrying_balance,10000.0,5.230500,3.327623,0.00,3.0000,5.000,7.0000,4.300000e+01
num_mort_accounts,10000.0,1.383100,1.717274,0.00,0.0000,1.000,2.0000,1.400000e+01
account_never_delinq_percent,10000.0,94.648990,9.155059,14.30,92.6000,100.000,100.0000,1.000000e+02
tax_liens,10000.0,0.043300,0.593852,0.00,0.0000,0.000,0.0000,5.200000e+01
public_record_bankrupt,10000.0,0.123800,0.337172,0.00,0.0000,0.000,0.0000,3.000000e+00
loan_amount,10000.0,16361.922500,10301.956759,1000.00,8000.0000,14500.000,24000.0000,4.000000e+04
term,10000.0,43.272000,11.029877,36.00,36.0000,36.000,60.0000,6.000000e+01
interest_rate,10000.0,12.427524,5.001105,5.31,9.4300,11.980,15.0500,3.094000e+01
installment,10000.0,476.205323,294.851627,30.75,256.0400,398.420,644.6900,1.566590e+03
balance,10000.0,14458.916610,9964.561865,0.00,6679.0650,12379.495,20690.1825,4.000000e+04
paid_total,10000.0,2494.234773,3958.230365,0.00,928.7000,1563.300,2616.0050,4.163044e+04
paid_principal,10000.0,1894.448466,3884.407175,0.00,587.1000,984.990,1694.5550,4.000000e+04
paid_interest,10000.0,599.666781,517.328062,0.00,221.7575,446.140,825.4200,4.216440e+03
paid_late_fees,10000.0,0.119516,1.813468,0.00,0.0000,0.000,0.0000,5.298000e+01

In [15]:
df[['annual_income',
    'debt_to_income',
    'loan_amount',
    'interest_rate',
    'installment',
    'total_credit_limit',
    'total_credit_utilized',
    'paid_total',
    'paid_principal',
    'paid_interest',
    'paid_late_fees']].describe()

,annual_income,debt_to_income,loan_amount,interest_rate,installment,total_credit_limit,total_credit_utilized,paid_total,paid_principal,paid_interest,paid_late_fees
count,1.000000e+04,9976.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,7.922215e+04,19.308192,16361.922500,12.427524,476.205323,1.836062e+05,51049.063100,2494.234773,1894.448466,599.666781,0.119516
std,6.473429e+04,15.004851,10301.956759,5.001105,294.851627,1.876327e+05,53636.731172,3958.230365,3884.407175,517.328062,1.813468
min,0.000000e+00,0.000000,1000.000000,5.310000,30.750000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.500000e+04,11.057500,8000.000000,9.430000,256.040000,5.159375e+04,19185.500000,928.700000,587.100000,221.757500,0.000000
50%,6.500000e+04,17.570000,14500.000000,11.980000,398.420000,1.146670e+05,36927.000000,1563.300000,984.990000,446.140000,0.000000
75%,9.500000e+04,25.002500,24000.000000,15.050000,644.690000,2.675500e+05,65421.000000,2616.005000,1694.555000,825.420000,0.000000
max,2.300000e+06,469.090000,40000.000000,30.940000,1566.590000,3.386034e+06,942456.000000,41630.443680,40000.000000,4216.440000,52.980000

In [16]:
df['loan_status'].value_counts(normalize=True) * 100

loan_status
Current               93.75
Fully Paid             4.47
In Grace Period        0.67
Late (31-120 days)     0.66
Late (16-30 days)      0.38
Charged Off            0.07
Name: proportion, dtype: float64